# Grammars
# MIR-PHRASE = {<MIR|MIR-SHORT><NN>*} 
# CANCER-PHRASE =  {<DT>*<JJ>*<CANCER><NN>*}
# EXP-N-PHRASE = {<DT>*<JJ>*<EXP-N><IN>?}
# EXP-PASSIVE-PHRASE = {<EXP-V>}
# EXP-ADJ-PHRASE = {<><EXP-ADJ><NN>}

